// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiTXHFATDv0MwtlnJVEKoxn9IRDxuNevM',
    appId: '1:732759318938:web:490fb67abb46cfa6d79a23',
    messagingSenderId: '732759318938',
    projectId: 'cobranca-app-dc317',
    authDomain: 'cobranca-app-dc317.firebaseapp.com',
    storageBucket: 'cobranca-app-dc317.firebasestorage.app',
    measurementId: 'G-SDWY913HVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlO45Y60uQyJ_KJp4ON9xQW_Dwwi4mGMQ',
    appId: '1:732759318938:android:7aa743ac7c345846d79a23',
    messagingSenderId: '732759318938',
    projectId: 'cobranca-app-dc317',
    storageBucket: 'cobranca-app-dc317.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlEQFNkguoNzwgBlv4n6b_IKa-i0dwqjw',
    appId: '1:732759318938:ios:29056fd609a433dfd79a23',
    messagingSenderId: '732759318938',
    projectId: 'cobranca-app-dc317',
    storageBucket: 'cobranca-app-dc317.firebasestorage.app',
    iosBundleId: 'com.example.appCobranca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlEQFNkguoNzwgBlv4n6b_IKa-i0dwqjw',
    appId: '1:732759318938:ios:29056fd609a433dfd79a23',
    messagingSenderId: '732759318938',
    projectId: 'cobranca-app-dc317',
    storageBucket: 'cobranca-app-dc317.firebasestorage.app',
    iosBundleId: 'com.example.appCobranca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiTXHFATDv0MwtlnJVEKoxn9IRDxuNevM',
    appId: '1:732759318938:web:76c9bebf477361b6d79a23',
    messagingSenderId: '732759318938',
    projectId: 'cobranca-app-dc317',
    authDomain: 'cobranca-app-dc317.firebaseapp.com',
    storageBucket: 'cobranca-app-dc317.firebasestorage.app',
    measurementId: 'G-6TT2M0QBF7',
  );
}
